### PR TITLE
Disable flatmapping except for community.general < 6.0.0 and community.network < 5.0.0

### LINKED ISSUE #132: Bad name for module in custom collection
With my team, we have a custom collection. In this collection we have custom modules. 

In particular, we have these directory layout : 

image

These modules must be called in our playbook with the entire directory names. For example, module **plugins/modules/cde/job.py** is called with **namespace.collection_name.<i>cde</i>.job**.

We're also building our documentation through **antsibull-docs**. 

Doing so we have a website with all our module documentation. However the name if the module name on the docs is not correctly set : in particular, we miss the intermediate directory name. For example, module **plugins/modules/cde/job.py** is referenced under **namespace.collection_name.job** (so without the ***cde*** directory). 

image

In conclusion, I think that there is an issue when the docs is created : it looks like it removes all intermediate directories in the module names.

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes #132.

I'm not sure whether it is worth adding an option to allow to enable it for specific collections. So for now, I've disabled it for all (except for c.g < 6.0.0 and c.n < 5.0.0).

### CODE REVIEW

**Comment by gotmax23** [comment]
IMO, we should either deprecate this functionality ("deprecation/feature removal: support for flatmapping has been removed. For now, it is kept as a special case for community.general < 6.0.0 and community.network <5.0.0") or make this configurable ("breaking change: this option is now disabled by default. As a special case, it is always enabled for community.general < 6.0.0 and community.network < 5.0.0")

**Comment by felixfontein** [comment]
I would like to make it configurable, but the **how** is the largest problem. This needs to be a per-collection configuration, but right now there is no way for a collection to say "please flatmap me".

**Comment by felixfontein** [comment]
Regarding configuring:
1. We cannot use MANIFEST.json / galaxy.yml.
2. Simply using `changelogs/config.yaml`'s value `flatmap` is kind of strange, since `changelogs/config.yaml` isn't really a config file for antsibull-docs.
3. Adding a new option to `docs/docsite/extra-docs.yml` or `docs/docsite/links.yml` seems even worse.
4. We could add a new file `docs/docsite/config.yml`. That could also be used for #31.
5. Waiting for something like https://github.com/ansible-community/community-topics/issues/154#issuecomment-1464590465 will probably take too long.

I'm currently tending to 4. WDYT?

**Comment by felixfontein** [comment]
Ok, I've now implemented 4.

**Review by gotmax23 — APPROVED** [review]
Ack

**Comment by felixfontein** [comment]
@gotmax23 thanks a lot for reviewing this!

**Pull request merged**
