### PR TITLE
Convert 'default', 'choices', 'sample' to type; change booleans to 'true' and 'false'

### PR DESCRIPTION
**Pull request by felixfontein**
Implements https://github.com/ansible-community/community-topics/issues/116

### CODE REVIEW

**Comment by felixfontein** [comment]
The part on converting `default`, `sample`, and `choices` is necessary since there are quite a few modules and plugins which use strings like `"yes"` to provide default values (or choices, or samples), instead of proper boolean values. Without this change, there were quite a few cases where for a boolean parameter / return value the choices are `true` and `false`, but the default is `yes`, `False`, or something else. (Strings with `False`, `True`, `false`, or `true` in them are already showing up wrong at the moment.)

**Comment by felixfontein** [comment]
You can find generated docs at https://ansible.fontein.de/collections/

**Review by Andersson007 — APPROVED** [review]
@felixfontein thanks for implementing the decision!

**Comment by felixfontein** [comment]
@Andersson007 thanks for reviewing this!

**Pull request merged**
