### PR TITLE
Allow to exclude ansible.builtin from 'current' subcommand

### PR DESCRIPTION
**Pull request by felixfontein**
Ref: #211.

### CODE REVIEW

**Review by briantist — APPROVED** [review]
This looks great to me! Only question I have is about whether it makes sense to allow excluding any number of arbitrary collections. It seems like the internal function is already changed for that, it would be a matter of exposing it with like `--excluded-collections` or something.

`--skip-ansible-builtin` is still a nice shorthand option to specifically skip that; I could understand not wanting to expose a wider exclude right now due to complexity/testing, just wondering if there was any other reason.

**Comment by felixfontein** [comment]
> Only question I have is about whether it makes sense to allow excluding any number of arbitrary collections. It seems like the internal function is already changed for that, it would be a matter of exposing it with like `--excluded-collections` or something.

I thought about exposing that, but I'm not sure it's a great interface. While it works OK for some specific situations, it's generally not a useful interface since more often you want to restrict to a specific set of collections, instead of excluding a specific set. The set of dependencies of a specific set of collections can change all the time, so if you exclude all dependencies there are *right now* the docs build in a month might suddenly include something you don't want it to include.

I think it's better to first try to figure out a better interface, and only allow this basic `--exlcluded-collections` if we cannot find a better way to do this.

**Comment by felixfontein** [comment]
@briantist thanks for reviewing this!

**Comment by briantist** [comment]
That's interesting, because you were thinking about excluding mostly for dependencies, and I wasn't even thinking about that (though it makes a lot of sense), I was thinking mostly about quickly building docs from and existing set of collections but also wanting to exclude certain ones even if they weren't dependencies... but I guess it's not going to be a common usage.

But I agree working out the interface(s) makes sense.

In a way, namespaces cold be more useful for building certain types of docsites. For example the one I'm building is internal and every collection is expected to use the same namespace. If collection names (for inclusion or exclusion) were wildcards, similar to how it is in the `antsibull-docs.cfg` file, that could be pretty versatile.

If I could do `antsibull-docs collection --use-current namespace.* other_ns.collection` or `antsibull-docs current --include-collections namespace.*` (maybe `--filter-collections`?) that would be cool.

**Comment by felixfontein** [comment]
Wildcard support for `antsibull-docs collection --use-current` sounds like a good idea. It's also something that can be implemented - first `ansible-galaxy collection list` can be used to get a list of all available collections (which is done anyway to figure out where the collections are located), and that can be used to figure out the actual list of collections.

**Pull request merged**
