### PR TITLE
Use doc_parsing_backend from app_ctx and not lib_ctx

### PR DESCRIPTION
**Pull request by felixfontein**
This is needed to make https://github.com/ansible-community/antsibull-core/pull/54 work fully. (Ref: https://github.com/ansible-community/antsibull-core/pull/59.)

### CODE REVIEW

**Comment by felixfontein** [comment]
(This passing CI before https://github.com/ansible-community/antsibull-core/pull/59 is merged shows that this fix works as intended.)

**Comment by felixfontein** [comment]
This is showing yet another problem: the extra docsite building tests install `Collecting antsibull-docs<2.0.0,>=1.0.0 (from -r requirements.txt (line 5))`...

**Comment by felixfontein** [comment]
Restarting tests.

**Review by gotmax23 — APPROVED** [review]
Ack. Thanks!

**Comment by felixfontein** [comment]
@gotmax23 thanks for reviewing and merging!

**Pull request merged**
