### PR TITLE
Fix module/role level version_added rendering

### PR DESCRIPTION
**Pull request by felixfontein**
There `_` is escaped and the escaping is visible in the rendered HTML, see for example https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/vault_kv2_get_module.html, https://docs.ansible.com/ansible/devel/collections/community/sap_libs/sap_snote_module.html, and https://docs.ansible.com/ansible/devel/collections/cloudscale_ch/cloud/network_module.html.

Thanks to @briantist for noticing and reporting this on IRC.

### CODE REVIEW

**Comment by felixfontein** [comment]
You can see the improved output here: https://ansible.fontein.de/collections/community/hashi_vault/vault_kv2_get_module.html#ansible-collections-community-hashi-vault-vault-kv2-get-module

**Review by briantist — APPROVED** [review]
thank you!

**Comment by felixfontein** [comment]
@briantist thanks for reviewing this!

**Comment by samccann** [comment]
fwiw, it used to say;
 `New in version 2.5.0: of community.hashi_vault
`
And now it says:
`New in version community.hashi_vault: 2.5.0`

I prefer the older way of putting the version first. Do we know why it changed?

**Comment by felixfontein** [comment]
@samccann this was changed in #34, not in this PR. The main reason this change happened was because all *other* version added texts were bad. That this one changed in this way wasn't intentional.

**Comment by felixfontein** [comment]
In any case, `New in version 2.5.0: of community.hashi_vault` isn't great either, since this basically says (using Sphinx's semantics) that the feature "of community.hashi_vault" was added in version 2.5.0.

**Comment by samccann** [comment]
ok thanks for the explanation. What do you think about `New in community.foo: version 2.4.0` as an enhancement in the future?

**Comment by felixfontein** [comment]
@samccann what do you think about `New in community.hashi_vault 2.5.0`, as in https://ansible.fontein.de/collections/community/hashi_vault/vault_kv2_get_module.html or https://ansible.fontein.de/collections/ansible/builtin/dnf_module.html ?

**Comment by felixfontein** [comment]
(I created #43 for this.)

**Pull request merged**
