### PR TITLE
Improve environment variable handling

### PR DESCRIPTION
**Pull request by felixfontein**
Improve environment variable handling:
- Use the correct Sphinx markup for environment variables (`envvar` role).
- Create an environment variable index.

Examples:
- Index: https://ansible.fontein.de/collections/environment_variables.html
- Enviornment variable in a plugin: https://ansible.fontein.de/collections/ansible/builtin/sh_shell.html#ansible-collections-ansible-builtin-sh-shell (click it!)

### CODE REVIEW

**Review by samccann — COMMENTED** [review]
Tested locally and looks good except the new index of environement variables isn't part of any TOC that I can see? should be be in the list of 'index of xxx' like modules, vars plugins etc?

We should also add a link to this from here? https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings

**Comment by felixfontein** [comment]
> Tested locally and looks good except the new index of environement variables isn't part of any TOC that I can see?

Yes, it would need to be added there somewhere.

> should be be in the list of 'index of xxx' like modules, vars plugins etc?

You mean in https://docs.ansible.com/ansible/devel/collections/all_plugins.html ? It would be a bit confusing if "Indexes of all modules and plugins" also contains an index of all environment variables. (On the other hand, that already contains an index of roles, but roles fit better in there than environment variables :) ) I'm not sure what the best place would be.

> We should also add a link to this from here? https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-configuration-settings

That requires a code change in ansible/ansible, but would be a good thing IMO.

**Review by samccann — APPROVED** [review]
docs and output LGTM

**Comment by felixfontein** [comment]
Ok, plan is to move the 'env variable fallback documentation for modules' to a separate PR so the uncontroversial part can be merged first.

**Comment by felixfontein** [comment]
I removed the module part (it is now a separate PR: #75).

**Comment by felixfontein** [comment]
@samccann thanks for reviewing this!

**Pull request merged**
