### PR TITLE
Fix toctrees for collection's index page

### PR DESCRIPTION
**Pull request by felixfontein**
As reported by @evgeni on IRC.

### CODE REVIEW

**Comment by evgeni** [comment]
This *looks* correct to me, but my Sphinx knowledge is a bit absent to do a full ack :)

**Comment by felixfontein** [comment]
Restarting CI.

**Comment by felixfontein** [comment]
I did test it with the foreman collection, and the result looked a lot better with this.

**Comment by felixfontein** [comment]
@evgeni thanks for reporting and reviewing!

**Pull request merged**
