### PR TITLE
Use <code> for default values, sample values, and choice values

### LINKED ISSUE #38: Use code formatting for all values (choice entries, defaults, samples)
Right now, while values in the description that are (correctly) formtated with `C(...)` have code / teletype formatting, other auto-generated values such as choice list entries, defaults, and samples, are formatted as regular text (only with different colors).

@briantist suggested (https://github.com/ansible-community/antsibull-docs/pull/36#issuecomment-1254335408) to format choice list entries also as code, and I extended that suggestion to format also defaults and samples values as code.

What do you think?

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes #38.

(The role setup code comes from #4.)

### CODE REVIEW

**Review by briantist — APPROVED** [review]
awesome! thanks for working on this @felixfontein

**Comment by felixfontein** [comment]
I rebased to incorporate the baseline tests; you can now see in the PR how the generated RST files will get updated by this PR.

**Comment by samccann** [comment]
Can't address the code but the output (based on the issue prototype) LGTM!

**Comment by felixfontein** [comment]
Thanks everyone who took a look and commented on this, no matter where :)

**Pull request merged**
