### PR TITLE
Allow to specify choices as dictionary instead of list

### PR DESCRIPTION
**Pull request by felixfontein**
Needed for the `combine` filter in ansible-core (https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/combine.yml#L26-L32).

### CODE REVIEW

**Comment by felixfontein** [comment]
Result: compare https://docs.ansible.com/ansible/devel/collections/ansible/builtin/combine_filter.html vs. https://ansible.fontein.de/collections/ansible/builtin/combine_filter.html#parameter-list_merge

Also, a side effect of this change: https://docs.ansible.com/ansible/devel/collections/community/crypto/openssl_csr_module.html#parameter-version vs https://ansible.fontein.de/collections/community/crypto/openssl_csr_module.html#parameter-version

**Comment by briantist** [comment]
This looks great, I saw the discussion in IRC and also never knew this was possible. Documenting choices that way is nice.

Only suggestion I have for the output is to have the choice values use `C()` format. That would be a departure from non-described choices unless we applied it to all of them... which I personally think we should, but I suppose that might need some discussion/voting.

**Comment by felixfontein** [comment]
@briantist I think that should apply to `default` as well. I'll do that in a different PR though (since I think that's separate enough), once this one is merged (to avoid conflicts).

**Comment by felixfontein** [comment]
@briantist @bcoca thanks for your comments!

**Pull request merged**
