### PR TITLE
pylint: complain about useless suppressions

### PR DESCRIPTION
**Pull request by felixfontein**

### CODE REVIEW

**Comment by gotmax23** [comment]
```
$ ./lint-pylint.sh
************* Module antsibull_docs.rstcheck
src/antsibull_docs/rstcheck.py:49:0: I0021: Useless suppression of 'no-member' (useless-suppression)
src/antsibull_docs/rstcheck.py:51:0: I0021: Useless suppression of 'no-member' (useless-suppression)
************* Module antsibull_docs.data.collection-enum
src/antsibull_docs/data/collection-enum.py:21:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:23:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:24:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:25:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:26:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:27:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:28:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:29:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:31:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:35:0: I0021: Useless suppression of 'import-error' (useless-suppression)
src/antsibull_docs/data/collection-enum.py:37:0: I0021: Useless suppression of 'import-error' (useless-suppression)
```

**Comment by felixfontein** [comment]
Hmm for some reason these are still not reported as errors. :/

**Comment by felixfontein** [comment]
(The difference might be that this is using an older version of pylint since it supports older versions of Python, and poetry's resolver only installs versions that support all Python versions the project supports. Which is very far off from what pip does. :roll_eyes:)

**Comment by gotmax23** [comment]
> (The difference might be that this is using an older version of pylint since it supports older versions of Python, and poetry's resolver only installs versions that support all Python versions the project supports. Which is very far off from what pip does. roll_eyes)

I opened https://github.com/ansible-community/antsibull-core/issues/38.

**Comment by felixfontein** [comment]
@gotmax23 thanks!

**Pull request merged**
