### PR TITLE
Adjust collection URLs for new Galaxy codebase

### LINKED ISSUE #147: Galaxy v3 API: update `collection_url` defaults
The current default is `{"*": "https://galaxy.ansible.com/{namespace}/{name}"}`, which will likely not work for arbitrary collections for the new Ansible Community Galaxy.

### PR DESCRIPTION
**Pull request by felixfontein**
Fixes #147.

### CODE REVIEW

**Comment by felixfontein** [comment]
The only current announcement for the switch I saw so far was in #social:ansible.com on September 21th, but there hasn't been a Bullhorn release since then.

CC @samccann @oraNod @rochacbruno @himdel

**Comment by himdel** [comment]
Looks good :+1:  (assuming the change only gets applied to collections, not roles)

**Comment by felixfontein** [comment]
@himdel antsibull-docs doesn't support standalone roles, so this is only used for content in collections anyway :)

**Comment by samccann** [comment]
Go live date for Galaxy to become GalaxyNG is Saturday Sept 30th.

**Comment by felixfontein** [comment]
The announcement is now live (in today's Bullhorn release): https://mailchi.mp/redhat/the-bullhorn-117

**Review by briantist — APPROVED** [review]

**Comment by felixfontein** [comment]
Plan: merge this once Galaxy switch happens, and create a new release with only this change (and potentially bugfixes that have been fixed by then).

**Comment by felixfontein** [comment]
(Rebasing to current `main`.)

**Comment by felixfontein** [comment]
Merging since the Galaxy codebase switch happened :tada:

**Pull request merged**
